development:
 sessions:
    default:
      hosts:
      - ds031098.mongolab.com:31098
      database: wishpandadb
      username: dmp623
      password: duc623
      options:
        skip_version_check: true
        safe: true

production:
 sessions:
    default:
      hosts:
      - ds031098.mongolab.com:31098
      database: wishpandadb
      username: dmp623
      password: duc623
      options:
        skip_version_check: true
        safe: true
      # uri: mongodb://dmp623:duc623@ds031098.mongolab.com:31098/wishpandadb
      # options:
      #   skip_version_check: true
      #   safe: true